<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-16T00:07:21 IST" name="Suite" finished-at="2020-10-16T00:07:37 IST" duration-ms="16556">
    <groups>
    </groups>
    <test started-at="2020-10-16T00:07:21 IST" name="Test" finished-at="2020-10-16T00:07:37 IST" duration-ms="16556">
      <class name="com.nopCommerce.TestCases.TC_Login_001">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.nopCommerce.TestCases.TC_Login_001@71b1176b]" started-at="2020-10-16T00:07:21 IST" name="setup" finished-at="2020-10-16T00:07:30 IST" duration-ms="8825" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest()[pri:0, instance:com.nopCommerce.TestCases.TC_Login_001@71b1176b]" started-at="2020-10-16T00:07:30 IST" name="loginTest" finished-at="2020-10-16T00:07:37 IST" duration-ms="6330" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.nopCommerce.TestCases.TC_Login_001.loginTest(TC_Login_001.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.nopCommerce.TestCases.TC_Login_001@71b1176b]" started-at="2020-10-16T00:07:37 IST" name="tearDown" finished-at="2020-10-16T00:07:37 IST" duration-ms="708" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.nopCommerce.TestCases.TC_Login_001 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
